export const MONGO_CONNECTION = 'MONGO_CONNECTION';
export const USERS_MODEL = 'USERS_MODEL';
export const ORDERS_MODEL = 'ORDERS_MODEL';
export const POLICIES_MODEL = 'POLICIES_MODEL';
export const COMPANIES_MODEL = 'COMPANIES_MODEL';
